"""Firmware macro generation for RoboStudio hardware configuration (H25-C)."""

from pathlib import Path
from typing import Optional

from .device_registry import DeviceRegistry
from .hardware_config import HardwareConfig


class HardwareMacroGenerator:
    """Generates the firmware feature macro header from HardwareConfig.

    The generated header is intentionally deterministic: every registered device
    always receives an explicit 0/1 macro, including devices disabled by default.
    """

    HEADER_GUARD = "ROBOT_PLATFORM_GENERATED_DEVICE_CONFIG_H"

    def macro_name(self, device_id: str) -> str:
        return "ROBOT_FEATURE_" + device_id.upper()

    def render(self, config: HardwareConfig) -> str:
        lines = [
            "// AUTO-GENERATED FILE. DO NOT EDIT.",
            "// Generated by RoboStudio HardwareMacroGenerator (H25-C).",
            "#pragma once",
            "",
        ]

        categories = []
        for device in DeviceRegistry.all():
            if device.category not in categories:
                categories.append(device.category)

        for category in categories:
            lines.append(f"// {category.upper()}")
            for device in DeviceRegistry.by_category(category):
                enabled = 1 if config.is_enabled(device.device_id) else 0
                lines.append(f"#define {self.macro_name(device.device_id):<32} {enabled}")
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def generate(self, config: HardwareConfig, output_path: Path) -> Path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.render(config), encoding="utf-8")
        return output_path

    @classmethod
    def default_output_path(cls) -> Path:
        workspace_root = Path(__file__).resolve().parent.parent.parent
        return (
            workspace_root
            / "robot-platform"
            / "main"
            / "include"
            / "generated"
            / "generated_device_config.h"
        )
