# compiler/binary/layout.py
# Binary layout constants

MAGIC = 0x4E494252
ABI_VERSION = 1
INSTRUCTION_SET_VERSION = 1

# Operand type tags (dùng trong constant pool và operand encoding)
OPERAND_TYPE_INTEGER = 0x01
OPERAND_TYPE_FLOAT = 0x02
OPERAND_TYPE_BOOLEAN = 0x03
OPERAND_TYPE_STRING = 0x04
OPERAND_TYPE_ENUM = 0x05
OPERAND_TYPE_REGISTER = 0x06
OPERAND_TYPE_LABEL = 0x07
OPERAND_TYPE_CONSTANT_POOL = 0x08