; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: board folding, storage size
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Upload port - can be overridden with --upload-port
upload_port = COM4

; Monitor settings
monitor_speed = 115200

; Build flags
build_flags =
    -I src
    -I src/Application
    -I src/Behavior
    -I src/Communication
    -I src/Devices
    -I src/Diagnostic
    -I src/Drivers
    -I src/HardwareAbstraction
    -I src/Logger
    -I src/Services/Robot
    -I src/Services/VM
    -I include/generated

; Source files
src_filter = +<src/*>

; Lib dependencies (nếu cần)
lib_deps =
    ; Có thể thêm thư viện nếu cần