import json
import os
from pathlib import Path

Import("env")

# Credentials can come from a local bootstrap artifact generated by
# RoboStudio, or from the existing process environment. Bootstrap artifacts
# are intentionally outside Git and are consumed only during first-flash.
config_path = os.getenv("ROBOT_BOOTSTRAP_CONFIG", "").strip()
ssid = os.getenv("ROBOT_WIFI_SSID", "")
password = os.getenv("ROBOT_WIFI_PASSWORD", "")
ota_password = os.getenv("ROBOT_OTA_PASSWORD", "")

if config_path:
    path = Path(config_path).expanduser().resolve()
    if not path.is_file():
        raise RuntimeError(f"ROBOT_BOOTSTRAP_CONFIG not found: {path}")
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"Invalid ROBOT_BOOTSTRAP_CONFIG: {exc}") from exc

    if config.get("type") != "antechkids.robot.bootstrap":
        raise RuntimeError("Unsupported robot bootstrap config type")
    if config.get("schema_version") != 1:
        raise RuntimeError("Unsupported robot bootstrap schema version")

    wifi = config.get("wifi", {})
    ota = config.get("ota", {})
    ssid = str(wifi.get("ssid", "")).strip()
    password = str(wifi.get("password", ""))
    ota_password = str(ota.get("password", ""))

# OTA builds must be explicitly provisioned. Never fall back to a shared/default
# credential because every classroom robot must have an intentional OTA secret.
if env.get("PIOENV") == "esp32dev_ota" and not ota_password:
    raise RuntimeError(
        "ROBOT_OTA_PASSWORD must be set for esp32dev_ota builds; "
        "no shared/default credential is permitted"
    )

# First-flash builds must carry a generated bootstrap artifact. The firmware
# copies these values into NVS on first boot and subsequently uses NVS values.
if env.get("PIOENV") == "esp32dev_bootstrap":
    if not config_path:
        raise RuntimeError(
            "ROBOT_BOOTSTRAP_CONFIG must be set for esp32dev_bootstrap builds"
        )
    if not ssid or not ota_password:
        raise RuntimeError("Bootstrap config must contain Wi-Fi SSID and OTA password")

    env.Append(CPPDEFINES=[("ROBOT_BOOTSTRAP_PROVISIONED", "1")])

env.Append(CPPDEFINES=[
    ("ROBOT_WIFI_SSID", env.StringifyMacro(ssid)),
    ("ROBOT_WIFI_PASSWORD", env.StringifyMacro(password)),
    ("ROBOT_OTA_PASSWORD", env.StringifyMacro(ota_password)),
])
