"""Shared hardware feature contract for RoboStudio and deployment tools.

This module deliberately lives under ``tools`` because the production release
ships these Python tools for deployment, while RoboStudio itself is packaged as
an executable. Keeping device metadata, header rendering, and current-user
hardware state resolution here prevents source-mode and packaged-mode behavior
from drifting apart.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping

from tools import runtime_paths

HARDWARE_CONFIG_VERSION = 1
GENERATED_HEADER_RELATIVE = Path("generated") / "generated_device_config.h"
USER_HARDWARE_CONFIG_NAME = "hardware.json"


@dataclass(frozen=True)
class HardwareFeatureDefinition:
    device_id: str
    display_name: str
    category: str
    default_enabled: bool
    description: str


HARDWARE_FEATURES: tuple[HardwareFeatureDefinition, ...] = (
    HardwareFeatureDefinition(
        "motor",
        "Motor",
        "motion",
        True,
        "Main left/right drive motors.",
    ),
    HardwareFeatureDefinition(
        "encoder",
        "Motor Encoder",
        "motion",
        False,
        "Wheel or motor feedback encoder support.",
    ),
    HardwareFeatureDefinition(
        "line_sensor",
        "Line Sensor",
        "sensors",
        True,
        "Reflective line sensor array.",
    ),
    HardwareFeatureDefinition(
        "ultrasonic",
        "Ultrasonic Sensor",
        "sensors",
        True,
        "Distance measurement sensor.",
    ),
    HardwareFeatureDefinition(
        "imu",
        "MPU6050 IMU",
        "sensors",
        False,
        "Inertial measurement unit for heading and motion assistance.",
    ),
    HardwareFeatureDefinition(
        "servo",
        "Servo",
        "expansion",
        False,
        "Servo actuator support.",
    ),
    HardwareFeatureDefinition(
        "buzzer",
        "Buzzer",
        "expansion",
        True,
        "Audio/buzzer output support.",
    ),
)

_BY_ID = {feature.device_id: feature for feature in HARDWARE_FEATURES}


class HardwareFeatureConfigError(RuntimeError):
    """Raised when hardware state cannot be normalized or generated safely."""


def feature_ids() -> tuple[str, ...]:
    return tuple(feature.device_id for feature in HARDWARE_FEATURES)


def defaults() -> dict[str, bool]:
    return {
        feature.device_id: bool(feature.default_enabled)
        for feature in HARDWARE_FEATURES
    }


def macro_name(device_id: str) -> str:
    if device_id not in _BY_ID:
        raise KeyError(f"Unknown device: {device_id}")
    return "ROBOT_FEATURE_" + device_id.upper()


def normalize_hardware_payload(data: Any) -> dict[str, bool]:
    """Normalize hardware.json using the same semantics as RoboStudio domain state.

    Missing known devices receive their registered defaults. Unknown devices are
    rejected so a stale/newer configuration cannot silently influence firmware.
    Both the current boolean form and the historical ``{"enabled": ...}`` form
    are accepted.
    """
    if not isinstance(data, dict):
        raise ValueError("Hardware configuration must be a JSON object")

    version = data.get("version", HARDWARE_CONFIG_VERSION)
    try:
        version = int(version)
    except (TypeError, ValueError) as exc:
        raise ValueError("Hardware configuration version must be an integer") from exc
    if version != HARDWARE_CONFIG_VERSION:
        raise ValueError(f"Unsupported hardware configuration version: {version}")

    raw_devices = data.get("devices", {})
    if not isinstance(raw_devices, dict):
        raise ValueError("'devices' must be an object")

    state = defaults()
    for device_id, raw in raw_devices.items():
        if device_id not in _BY_ID:
            raise ValueError(f"Unknown device: {device_id}")
        if isinstance(raw, bool):
            enabled = raw
        elif isinstance(raw, dict) and "enabled" in raw:
            enabled = bool(raw["enabled"])
        else:
            raise ValueError(
                f"Device '{device_id}' must be a boolean or object with 'enabled'"
            )
        state[device_id] = bool(enabled)
    return state


def render_generated_header(devices: Mapping[str, bool]) -> str:
    """Render the deterministic firmware feature header."""
    normalized = defaults()
    for device_id, enabled in devices.items():
        if device_id not in _BY_ID:
            raise ValueError(f"Unknown device: {device_id}")
        normalized[device_id] = bool(enabled)

    lines = [
        "// AUTO-GENERATED FILE. DO NOT EDIT.",
        "// Generated by RoboStudio HardwareMacroGenerator (H25-C).",
        "#pragma once",
        "",
    ]
    categories: list[str] = []
    for feature in HARDWARE_FEATURES:
        if feature.category not in categories:
            categories.append(feature.category)

    for category in categories:
        lines.append(f"// {category.upper()}")
        for feature in HARDWARE_FEATURES:
            if feature.category != category:
                continue
            enabled = 1 if normalized[feature.device_id] else 0
            lines.append(f"#define {macro_name(feature.device_id):<32} {enabled}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def user_hardware_config_path() -> Path:
    """Return the one mutable hardware source-of-truth path for all modes."""
    return runtime_paths.user_data_root() / USER_HARDWARE_CONFIG_NAME


def generated_header_path() -> Path:
    """Return the one mutable generated-header path for source and packaged mode."""
    return runtime_paths.user_data_root() / GENERATED_HEADER_RELATIVE


def application_default_candidates() -> tuple[Path, ...]:
    """Return read-only default config locations for packaged and source layouts."""
    app = runtime_paths.application_root()
    return (
        app / "config" / USER_HARDWARE_CONFIG_NAME,
        app / "robostudio" / "config" / USER_HARDWARE_CONFIG_NAME,
    )


def load_current_hardware_devices(
    *,
    user_config: Path | None = None,
    default_candidates: Iterable[Path] | None = None,
) -> dict[str, bool]:
    """Load current hardware state with fail-safe default fallback.

    This mirrors RoboStudio's persistence policy: writable user state wins; an
    invalid/missing user file falls back to immutable application defaults; if
    no default file is available, registered feature defaults are used.
    """
    user = Path(user_config or user_hardware_config_path()).expanduser()
    candidates = [user]
    if default_candidates is None:
        candidates.extend(application_default_candidates())
    else:
        candidates.extend(Path(path).expanduser() for path in default_candidates)

    for path in candidates:
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
            return normalize_hardware_payload(payload)
        except (OSError, json.JSONDecodeError, ValueError, TypeError):
            continue
    return defaults()


def write_generated_header(devices: Mapping[str, bool], output: Path | None = None) -> Path:
    """Atomically write a generated feature header into mutable state."""
    destination = Path(output or generated_header_path()).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    temp = destination.with_name(destination.name + f".tmp-{os.getpid()}")
    try:
        temp.write_text(render_generated_header(devices), encoding="utf-8")
        os.replace(temp, destination)
    except OSError as exc:
        try:
            temp.unlink(missing_ok=True)
        except OSError:
            pass
        raise HardwareFeatureConfigError(
            f"Unable to write generated hardware header {destination}: {exc}"
        ) from exc
    return destination


def regenerate_user_device_config_header() -> Path:
    """Regenerate derived firmware macros from the current hardware source of truth."""
    devices = load_current_hardware_devices()
    return write_generated_header(devices)
